# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {C:/Users/Silicon Photonic/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-4368-Cacuy/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/fft-parallel4/verilog/topfft/topfft.cache/wt [current_project]
set_property parent.project_path C:/fft-parallel4/verilog/topfft/topfft.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/fft-parallel4/verilog/topfft/topfft.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/BF.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/Blq.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/D_reg.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/D_reg_1.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff0.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff1.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff2.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff3.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff4.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff_data0.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff_data1.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff_data2.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff_data3.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/coeff_data4.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/contador.v
  C:/fft-parallel4/verilog/pruebaPF/pruebaPF.srcs/sources_1/new/fixtop_sat.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/multip.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/sat.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/switch.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/topD.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/topD_1.v
  C:/fft-parallel4/verilog/topfft/topfft.srcs/sources_1/new/topfft.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top topfft -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef topfft.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file topfft_utilization_synth.rpt -pb topfft_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
