webtalk_init -webtalk_dir /media/kevinvig7/Elements/Documentos/CursoVLSI/TP_Final/Verilog/Mult_CSD/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/CSD_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jun 13 21:40:56 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6684078a-fb9f-4701-a1bf-84804e0afad7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e2a404b817fd410789c9dbb01d682f10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "49" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19 Tara" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1414.442 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129256_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2916155600 -regid "" -xml /media/kevinvig7/Elements/Documentos/CursoVLSI/TP_Final/Verilog/Mult_CSD/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/CSD_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/kevinvig7/Elements/Documentos/CursoVLSI/TP_Final/Verilog/Mult_CSD/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/CSD_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/kevinvig7/Elements/Documentos/CursoVLSI/TP_Final/Verilog/Mult_CSD/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/CSD_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
