webtalk_init -webtalk_dir /home/dani6rg/Documentos/ProyectosXILINX/ChannelModelHardware/ChannelTruncado/ChannelTruncado.sim/sim_1/behav/xsim/xsim.dir/tb_ChannelTruncado_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec  7 07:23:04 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "71faa94d6e305f7ba9e4add65f48ddd5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ea246b40d7384de88983ffec4e8ac3d4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3100.307 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "101580 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129004_KB" -context "xsim\\usage"
webtalk_transmit -clientid 120722240 -regid "" -xml /home/dani6rg/Documentos/ProyectosXILINX/ChannelModelHardware/ChannelTruncado/ChannelTruncado.sim/sim_1/behav/xsim/xsim.dir/tb_ChannelTruncado_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/dani6rg/Documentos/ProyectosXILINX/ChannelModelHardware/ChannelTruncado/ChannelTruncado.sim/sim_1/behav/xsim/xsim.dir/tb_ChannelTruncado_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/dani6rg/Documentos/ProyectosXILINX/ChannelModelHardware/ChannelTruncado/ChannelTruncado.sim/sim_1/behav/xsim/xsim.dir/tb_ChannelTruncado_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
